### ISSUE TITLE
Query by object property crashes system

### ISSUE THREAD

**Issue by philipobrien** [OPENi-ict/object-api#20]
There is an object with the following as it's data

```
"@data": {
       "name": "Philip O'Brien"
   }
```

If I try to `GET /objects/{cloudletId}/{objectId}/{property}` with *name* as the property it crashes the cloudlet platform

```
[TypeError: Cannot read property '@data' of undefined]
TypeError: Cannot read property '@data' of undefined
    at processSubObjects (/home/vagrant/repos/dao/lib/CBasehelper.js:894:36)
    at processGetData (/home/vagrant/repos/dao/lib/CBasehelper.js:1064:10)
    at /home/vagrant/repos/dao/lib/CBasehelper.js:757:13
```

While the query might not be correct, some checks are required to cause it just to fail rather than crash

**Comment by dmccarthy-dev** [comment]
Added a check to see if property exists and returns empty if it doesn't (as opposed to crashing the system)
